# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gift}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nicholas Bruning"]
  s.date = %q{2010-03-18}
  s.default_executable = %q{gift}
  s.description = %q{Gift provides a simple interface for pushing your site to a server that does not support git, via FTP.}
  s.email = %q{nicholas@bruning.com.au}
  s.executables = ["gift"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gift/recipients.yml",
     ".gitignore",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/gift.rb",
     "gift.gemspec",
     "lib/cli.rb",
     "lib/recipient.rb"
  ]
  s.homepage = %q{http://github.com/thetron/gift}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Git and FTP, the easy way.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ptools>, [">= 1.1.8"])
      s.add_runtime_dependency(%q<git>, [">= 1.2.5"])
    else
      s.add_dependency(%q<ptools>, [">= 1.1.8"])
      s.add_dependency(%q<git>, [">= 1.2.5"])
    end
  else
    s.add_dependency(%q<ptools>, [">= 1.1.8"])
    s.add_dependency(%q<git>, [">= 1.2.5"])
  end
end

